import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (!('documentPictureInPicture' in window)) {
                window.documentPictureInPicture = {};
              }
            `,
          }}
        />
        <nav className="p-5 border-b border-gray-300">
          <a href="/medicos" className="mr-4 text-blue-600 hover:underline">Médicos</a>
          <a href="/pacientes" className="mr-4 text-blue-600 hover:underline">Pacientes</a>
          <a href="/citas" className="mr-4 text-blue-600 hover:underline">Citas</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
